name: "Test Generating"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}